{
 "title": "EKS Service Jvm",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "query_result(sum by(namespace)(rate(jvm_memory_used_bytes[5m])))"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "query_result(sum by(mobiu_service)(rate(jvm_memory_used_bytes{namespace=\"$cluster\"}[5m])))"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "query_result(sum by(id)(rate(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\", area=\"heap\"}[5m])))"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "query_result(sum by(id)(rate(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\", area=\"nonheap\"}[5m])))"
   },
   {
    "name": "service_name_no_version",
    "query": "query_result(sum by(mobiu_service)(rate(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\"}[5m])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "options": {
    "content": "- 除了 IO 指标是所有容器的总和\n- 其他指标都是所有容器的均值"
   },
   "content": "- 除了 IO 指标是所有容器的总和\n- 其他指标都是所有容器的均值"
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, uri)(rate(http_server_requests_seconds_count{namespace=\"$cluster\", mobiu_service=\"$service_name\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{namespace=\"$cluster\", mobiu_service=\"$service_name\", status=~\"5..\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_sum{namespace=\"$cluster\", mobiu_service=\"$service_name\",status!~\"5..\"}[1m]))/sum by(uri)(rate(http_server_requests_seconds_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG {{uri}}"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(mobiu_service) (tomcat_threads_busy{namespace=\"$cluster\", mobiu_service=\"$service_name\"})or avg by(service_name) (tomcat_threads_busy_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "TOMCAT - BUSY"
    },
    {
     "expr": "avg by(mobiu_service)(tomcat_threads_current{namespace=\"$cluster\", mobiu_service=\"$service_name\"}) or avg by(service_name)(tomcat_threads_current_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "avg(tomcat_threads_config_max{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(tomcat_threads_config_max_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "TOMCAT - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "used"
    },
    {
     "expr": "max(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "committed"
    },
    {
     "expr": "max(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(jvm_memory_used_bytes{area=\"nonheap\", namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "max(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(sum by(instance)(process_memory_rss_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "rss"
    },
    {
     "expr": "avg(sum by(instance)(process_memory_pss_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "pss"
    },
    {
     "expr": "avg(sum by(instance)(process_memory_swap_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "swap"
    },
    {
     "expr": "avg(sum by(instance)(process_memory_swappss_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "swappss"
    },
    {
     "expr": "avg(sum by(instance)(process_memory_pss_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})) + avg(sum by(instance)(process_memory_swap_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}))",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_usage{namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "system"
    },
    {
     "expr": "avg(process_cpu_usage{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "process"
    },
    {
     "expr": "avg(avg_over_time(process_cpu_usage{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1h]))",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_load_average_1m{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system-1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(system_cpu_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_threads_live{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(jvm_threads_live_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "live"
    },
    {
     "expr": "avg(jvm_threads_daemon{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(jvm_threads_daemon_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "daemon"
    },
    {
     "expr": "avg(jvm_threads_peak{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(jvm_threads_peak_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "peak"
    },
    {
     "expr": "avg(process_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(state)(jvm_threads_states_threads{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(rate(logback_events_total{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(process_open_fds{namespace=\"$cluster\", mobiu_service=\"$service_name\"})",
     "legendFormat": "open"
    },
    {
     "expr": "avg(process_files_open{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(process_files_open_files{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"$jvm_memory_pool_heap\"}))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum by(instance)(jvm_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "used"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_committed_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(sum by(instance)(jvm_memory_max_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=~\"$jvm_memory_pool_nonheap\"}))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by(action, cause)(rate(jvm_gc_pause_seconds_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg (rate(jvm_gc_pause_seconds_sum{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))/ avg (rate(jvm_gc_pause_seconds_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "avg(jvm_gc_pause_seconds_max{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))",
       "legendFormat": "allocated"
      },
      {
       "expr": "avg(rate(jvm_gc_memory_promoted_bytes_total{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[1m]))",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_classes_loaded{namespace=\"$cluster\", mobiu_service=\"$service_name\",}) or avg(jvm_classes_loaded_classes{namespace=\"$cluster\", mobiu_service=\"$service_name\",})",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, mobiu_service)(delta(jvm_classes_loaded{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[5m])) or sum by(namespace, mobiu_service)(delta(jvm_classes_loaded_classes{namespace=\"$cluster\", mobiu_service=\"$service_name\",}[5m]))",
       "legendFormat": "load"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\", id=\"direct\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\", id=\"direct\"})",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"direct\"}) or avg(jvm_buffer_count_buffers{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"direct\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"mapped\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"mapped\"})",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_count{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"mapped\"}) or avg(jvm_buffer_count_buffers{namespace=\"$cluster\", mobiu_service=\"$service_name\",id=\"mapped\"})",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}