{
 "title": "MobiuKafka Stats",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "business_group",
    "label": "business_group",
    "query": "label_values(kafka_topic_partition_current_offset, business_group)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_topic_partition_current_offset{business_group=~\"$business_group\",topic!=\"__consumer_offsets\"}, topic)"
   },
   {
    "name": "consumergroup",
    "label": "consumergroup",
    "query": "label_values(kafka_consumergroup_current_offset{business_group=~\"$business_group\", topic=~\"$topic\"}, consumergroup)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kafka_network_requestmetrics_total_total{job=~\"$business_group\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "MobiuKafka common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "leaders",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader{topic=~\"$topic\", business_group=~\"$business_group\"})"
    }
   ]
  },
  {
   "title": "replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_replicas{topic=~\"$topic\",business_group=~\"$business_group\"})"
    }
   ]
  },
  {
   "title": "in sync replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(topic)(kafka_topic_partition_in_sync_replica{topic=~\"$topic\", business_group=~\"$business_group\"})"
    }
   ]
  },
  {
   "title": "idle time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_handlerpool_oneminute_rate{job=~\"$business_group\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "topic message in per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{business_group=~\"$business_group\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "consumer message in per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{business_group=~\"$business_group\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"}[1m])/60) by (consumergroup, topic) >0",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "lag by  consumer group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(kafka_consumergroup_lag{business_group=~\"$business_group\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"}) by (consumergroup, topic), 0)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "partition offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(partition)(kafka_consumergroup_current_offset{business_group=~\"$business_group\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"})",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "topic in / out bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesinpersec{business_group=~\"$business_group\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "-sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{business_group=~\"$business_group\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "out"
    },
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesrejectedpersec{business_group=~\"$business_group\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "jvm memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=~\"$business_group\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gc time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(rate(jvm_gc_collection_seconds_sum{job=\"$business_group\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MobiuKafka response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests total time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_total_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests total time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_total_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests local time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_local_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests local time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_local_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests remote time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_remote_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests remote time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_remote_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "throttle time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_throttle_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "throttle time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_throttle_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "response send time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_responsesend_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "respnse send time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_responsesend_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "request queue time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_requestqueue_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "request queue time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_requestqueue_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "response queue time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms", "label": "avg" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_responsequeue_total{kind=\"mean\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "response queue time top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "ms", "label": ".99" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by(request)(avg_over_time(kafka_network_requestmetrics_responsequeue_total{kind=\"99thpercentile\",job=~\"$business_group\",instance=~\"$instance\",request!=\"Fetch\"}[1m])))",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MobiuKafka requests count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests per second",
     "type": "graph",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requests_count_total{job=~\"$business_group\",request!=\"Fetch\"}[1m])) by(request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "requests count",
     "type": "graph",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_network_requests_count_total{job=~\"$business_group\",request!=\"Fetch\"}) by(request)",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  }
 ]
}