{
 "title": "Kube Containers Basic Performance",
 "description": "Kube Containers Basic Performance",
 "tags": [
  "prometheus",
  "capacity"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster Name", "query": "container_tasks_state" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "query_result(container_tasks_state{namespace=\"$cluster_name\", container!=\"POD\", container!=\"istio-proxy\"})"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Services of the Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by (container) (container_tasks_state{namespace=~\"$cluster_name\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Pods of the Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod)(container_tasks_state{namespace=~\"$cluster_name\",state=\"running\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Pods of Service(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod)(container_tasks_state{namespace=~\"$cluster_name\", container=~\"$service_name\",state=\"running\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Pods of Service(s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(sum by (pod)(container_tasks_state{namespace=~\"$cluster_name\", container=~\"$service_name\", state=\"running\"})) by (pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pod}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "CPU Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Notice",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "Notice: ` not inlcude istio-proxy`"
   },
   "content": "Notice: ` not inlcude istio-proxy`"
  },
  {
   "title": "Cluster CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}) / 100 / 1024",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization of the Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}[$interval])) by (namespace) / (sum(container_spec_cpu_shares{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}) by(namespace) / 1024)",
     "legendFormat": "request usage"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}[$interval])) by (namespace))/ (sum(container_spec_cpu_quota{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}) by (namespace) / 100 / 1024)",
     "legendFormat": "limit usage"
    }
   ]
  },
  {
   "title": "Service(s) CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"$cluster_name\", container=~\"$service_name\"}) / 100 / 1024",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization of the Service(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=~\"$service_name\"}[$interval])) by (container) / (sum(container_spec_cpu_shares{namespace=\"$cluster_name\", container=~\"$service_name\"}) by(container) / 1024)",
     "legendFormat": "req usage -  {{container}}"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=~\"$service_name\"}[$interval])) by (container)) / (sum(container_spec_cpu_quota{namespace=\"$cluster_name\", container=~\"$service_name\"}) by (container) / 100 / 1024)",
     "legendFormat": "limit usage - {{container}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}) / 1024",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service(s) CPU Cores Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{namespace=\"$cluster_name\", container=~\"$service_name\"}) / 1024",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request CPU Utilization by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=~\"$service_name\"}[$interval])) / on (pod) group_left  sum by(pod)(container_spec_cpu_shares{namespace=\"$cluster_name\", container=~\"$service_name\"} / 1024 )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Limit CPU Utilization by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=~\"$service_name\"}[$interval])) / on (pod) group_left sum by(pod)(container_spec_cpu_quota{namespace=\"$cluster_name\", container=~\"$service_name\"} / 100 / 1024 )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request CPU Utilization of Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=\"istio-proxy\",pod=~\"$service_name.*\"}[$interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Limit CPU Utilization of Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(irate(container_cpu_usage_seconds_total{namespace=\"$cluster_name\", container=\"istio-proxy\", pod=~\"$service_name.*\"}[$interval])) / on (pod) group_left sum by(pod)(container_spec_cpu_quota{namespace=\"$cluster_name\", container=\"istio-proxy\",pod=~\"$service_name.*\"} / 100 / 1024)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Mem Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Notice",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "Notice: ` not include istio-proxy`"
   },
   "content": "Notice: ` not include istio-proxy`"
  },
  {
   "title": "Memory Utilization of Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace)(container_memory_rss{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}) / sum by(namespace)(container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"})",
     "legendFormat": "limit usage"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"})",
     "legendFormat": "limit bytes"
    }
   ]
  },
  {
   "title": "Memory Utilization of Service(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(container_memory_rss{namespace=\"$cluster_name\", container=~\"$service_name\"}) / sum by(container)(container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container=~\"$service_name\"})",
     "legendFormat": "limit usage - {{container}}"
    },
    {
     "expr": "sum by (container) (container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container=~\"$service_name\"})",
     "legendFormat": "limit bytes - {{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(container_memory_rss{namespace=\"$cluster_name\", container=~\"$service_name\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy Memory Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (container_spec_memory_limit_bytes{namespace=\"$cluster_name\", container=\"istio-proxy\", pod=~\"$service_name.*\"})"
    }
   ]
  },
  {
   "title": "Proxy Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(container_memory_rss{namespace=\"$cluster_name\", container=\"istio-proxy\", pod=~\"$service_name.*\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notice",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "Notice: ` not inlcude istio-proxy`"
     },
     "content": "Notice: ` not inlcude istio-proxy`"
    },
    {
     "title": "Network of Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$cluster_name\",container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}[$interval])) by(namespace)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "RX : {{namespace}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{namespace=\"$cluster_name\",container!=\"istio-proxy\", container=~\"^[[:alpha:]]*\"}[$interval])) by(namespace)",
       "legendFormat": "TX : {{namespace}}"
      }
     ]
    },
    {
     "title": "Network by Service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$cluster_name\", pod=~\"$service_name.*\", container_name=~\"[[:alpha:]]*\"}[$interval])) by(mobiu_service)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "RX :",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{namespace=\"$cluster_name\", pod=~\"$service_name.*\", container_name=~\"[[:alpha:]]*\"}[$interval])) by(mobiu_service)",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "Network by Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$cluster_name\",pod=~\"$service_name.*\", container_name=~\"[[:alpha:]]*\",}[$interval])) by(pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "RX : {{pod}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{namespace=\"$cluster_name\",pod=~\"$service_name.*\", container_name=~\"[[:alpha:]]*\",}[$interval])) by(pod)",
       "legendFormat": "TX : {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}