{
 "title": "Redis Status",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis",
  "capacity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "business_group",
    "label": "business_group",
    "query": "label_values(redis_connected_clients, business_group)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(redis_connected_clients{business_group=~\"$business_group\"}, addr)"
   },
   {
    "name": "addr",
    "query": "label_values(redis_connected_clients{business_group=~\"$business_group\"}, addr)"
   }
  ]
 },
 "panels": [
  { "title": "Basic activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by(addr)(redis_uptime_in_seconds{addr=\"$addr\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(addr)(redis_memory_used_bytes{addr=~\"$addr\"}  / redis_memory_max_bytes{addr=~\"$addr\"})"
    }
   ]
  },
  {
   "title": "Memory Rss",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(addr)(redis_memory_used_rss_bytes{addr=~\"$addr\"}  / redis_memory_max_bytes{addr=~\"$addr\"})"
    }
   ]
  },
  {
   "title": "connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(redis_connected_clients{addr=\"$addr\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum by(addr)(delta(redis_connections_received_total{addr=\"$addr\"}[1m]))",
     "legendFormat": "connection create"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(redis_memory_used_bytes{addr=~\"$addr\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by(addr)(redis_config_maxmemory{addr=~\"$addr\"})",
     "legendFormat": "config max"
    },
    {
     "expr": "sum by(addr)(redis_memory_max_bytes{addr=~\"$addr\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum by(addr)(redis_memory_used_rss_bytes{addr=~\"$addr\"})",
     "legendFormat": "used_rss"
    }
   ]
  },
  {
   "title": "mem_fragmentation_ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(redis_memory_fragmentation_ratio{addr=\"$addr\"}) or sum by(addr)(redis_mem_fragmentation_ratio{addr=\"$addr\"})",
     "legendFormat": "mem_fragmentation_ratio"
    },
    {
     "expr": "sum by(addr)(irate(redis_memory_fragmentation_ratio{addr=\"$addr\"}[1m])) or sum by(addr)(irate(redis_mem_fragmentation_ratio{addr=\"$addr\"}[1m]))",
     "legendFormat": "mem_fragmentation_ratio_irate"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "graph",
   "description": "Clients blocked while waiting on BLPOP, BRPOP, or BRPOPLPUSH",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_blocked_clients{addr=\"$addr\"}) by(addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Command latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(8, irate(redis_command_call_duration_seconds_sum{addr=~\"$addr\"}[1m])) / topk(8, irate(redis_command_call_duration_seconds_count{addr=~\"$addr\"}[1m]))",
     "legendFormat": "{{ cmd }}"
    },
    {
     "expr": "topk(8, irate(redis_commands_duration_seconds_total{addr=~\"$addr\"}[1m])) / topk(8, irate(redis_commands_total{addr=~\"$addr\"}[1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(rate(redis_commands_processed_total{business_group=~\"$business_group\", addr=~\"$addr\"}[1m]))",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(irate(redis_keyspace_hits_total{addr=\"$addr\"}[1m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum by(addr)(irate(redis_keyspace_misses_total{addr=\"$addr\"}[1m]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum by(addr)((irate(redis_keyspace_hits_total{addr=\"$addr\"}[1m]) > 0) / (irate(redis_keyspace_misses_total{addr=\"$addr\"}[1m]) + irate(redis_keyspace_hits_total{addr=\"$addr\"}[1m])))",
     "legendFormat": "hit percentages"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by(addr,cmd)(irate(redis_command_call_duration_seconds_count{addr=~\"$addr\"}[1m])))",
     "legendFormat": "{{ cmd }}"
    },
    {
     "expr": "topk(5, sum by(addr,cmd)(irate(redis_commands_duration_seconds_total{addr=~\"$addr\"}[1m])))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Slowlog Lengths",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(addr)(redis_slowlog_length{addr=\"st-rcmd-source-pt.001.redis.meta.aws:6379\"})",
     "legendFormat": "slowlog_length"
    },
    {
     "expr": "sum by(addr)(irate(redis_slowlog_length{addr=\"$addr\"}[1m]))",
     "legendFormat": "slowlog_length_irate"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Cpu info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_used_cpu_sys{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "sys"
    },
    {
     "expr": "sum(rate(redis_used_cpu_user{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(redis_used_cpu_sys_children{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "sys_children"
    },
    {
     "expr": "sum(rate(redis_used_cpu_user_children{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "user_children"
    },
    {
     "expr": "sum(rate(redis_cpu_sys_seconds_total{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "sys"
    },
    {
     "expr": "sum(rate(redis_cpu_user_seconds_total{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(redis_cpu_sys_children_seconds_total{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "sys_children"
    },
    {
     "expr": "sum(rate(redis_cpu_user_children_seconds_total{addr=~\"$addr\"}[1m])) by (addr)",
     "legendFormat": "user_children"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(addr,instance_type)(rate(redis_net_input_bytes_total{addr=\"$addr\"}[1m]))",
     "legendFormat": "input : {{addr}}"
    },
    {
     "expr": "sum by(addr,instance_type)(rate(redis_net_output_bytes_total{addr=\"$addr\"}[1m]))",
     "legendFormat": "output : {{addr}}"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Last Bgsave Duration Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{addr=\"$addr\"}",
     "legendFormat": "{{ addr }}"
    }
   ]
  },
  {
   "title": "Rdb Changes Since Last Save",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_changes_since_last_save{addr=\"$addr\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  }
 ]
}